import 'package:isar/isar.dart';

part 'isar_extension_source.g.dart'; // This file will be generated by build_runner

@collection
class IsarExtensionSource {
  // Isar's auto-incrementing primary key
  Id id = Isar.autoIncrement;

  // This is the unique identifier for the extension, e.g., "comick"
  @Index(unique: true, replace: true)
  late String sourceId;
  
  late String name;
  late String version;
  late String lang;
  late bool isEnabled;
}